spring.config.import=\
    classpath:/application-default.properties,\
    optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/,\
    optional:configtree:${LIFERAY_ROUTES_DXP}/

logging.level.root=INFO

rules.groovy.repository.path=/o/c/cxgroovyvalidations
